### PR TITLE
remove `#include <cpuid.h>` to prevent build error on MSYS2

### PR DESCRIPTION
**Pull request by osamu620**
@Jamaika1 Please give a comment if possible.

### CODE REVIEW

**Comment by Jamaika1** [comment]
I don't know what the error is for msys2. I know that I was able to compile with GCC 12.0 codec and running for Windows.
https://walbourn.github.io/directxmath-avx2/
https://www.sendspace.com/file/1qwzmb

**Comment by osamu620** [comment]
@Jamaika1 

GCC 10.3.0 in the latest MSYS2 reported an error: 
```
In file included from C:/Users/osamu/Documents/OpenHTJ2K/openHTJ2K/source/core/coding/coding_units.cpp:44:
C:/tools/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/include/cpuid.h:300:1: error: redefinition of 'int __get_cpuid_count(unsigned int, unsigned int, unsigned int*, unsigned int*, unsigned int*, unsigned int*)'
  300 | __get_cpuid_count (unsigned int __leaf, unsigned int __subleaf,
```

This error is simply due to the multiple inclusion of `cpuid.h`. 
Because `cpuid.h` has already been included in `utils.hpp` , I think the other inclusions are not mandatory.

Was the `cpuid.h` required to build the codec for your system? or you could successfully build the codec without `cpuid.h`?
If the latter, I will remove the inclusions except for `utils.hpp`

**Comment by Jamaika1** [comment]
I understand. There was a mistake. The codec needed intrin.h. Now theoretically it was not needed, but it annoys me why for gcc should be x86intrin.h 32bit and not 64bit for __x86_64__

**Comment by osamu620** [comment]
@Jamaika1 
Do you sueggest to include `intrin.h` instead of `x86intrin.h` for x64 environment?

**Comment by Jamaika1** [comment]
I am an amateur computer scientist, but ...
The latest version of GCC 12 includes intrin.h. I don't know the exact specification of gcc. Intrin.h has both cpuid.h and x86intrin.h in it. Earlier, I provided fixes for older versions of gcc that don't include intrin.h.
I haven't tested this solution
```
#if defined (_MSC_VER) II (defined (__ GNUC__) && (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__> = 120000))
#include <intrin.h>
#endif
```

**Comment by osamu620** [comment]
@Jamaika1 
Thanks for the explanation. I don't have a toolchain with GCC 12.
I'll make new commits to take these inclusion problems for MinGW into account. So I would like to close this PR.
